version: '3.8'

services:
  php:
    build: .
    image: etable/php7.2mysql
    volumes:
      - './sendorder:/var/www/html'
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      AWS_KEY: $AWS_KEY
      AWS_SECRET: $AWS_SECRET
      AWS_WEBSOCKET_MANAGEMENT_ENDPOINT: $AWS_WEBSOCKET_MANAGEMENT_ENDPOINT

  nginx:
    image: nginx
    ports:
      - 8980:8980
    links:
      - "php:php"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './sendorder:/var/www/html'