AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "On connect and on disconnect handler"

Resources:
  # Websocket API
  OrderWebsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: OrderWebsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  # On Connect
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrderWebsocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg

  # Integrating on connect lambda into aws
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrderWebsocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

  # On Disconnect lambda
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref OrderWebsocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  
  # Integrating OnDisconnect Lambda into websocket
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref OrderWebsocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref OrderWebsocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref OrderWebsocket

  # Where on_connect function is located into our source code
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: on_connect/
      Handler: index.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          - DB_HOST
          - DB_USER
          - DB_PASSWORD
          - DB_NAME
  
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrderWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

  # Where on_disconnect function is located into our source code
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: on_disconnect/
      Handler: index.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          - DB_HOST
          - DB_USER
          - DB_PASSWORD
          - DB_NAME
  
      
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - OrderWebsocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

Outputs:
  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref OrderWebsocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]